version: "3.9"

services:
  frontend:
    image: nginx:alpine
    container_name: ski_frontend
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ski

  php:
    image: php:8.3-fpm
    container_name: ski_frontend_php
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - ski

networks:
  ski:
    external: true
